# region imports
from __future__ import annotations
import statistics
from typing import Callable, Dict, List, Optional, Sequence

# endregion
"""
Runtime support for code generated by the score-code generator: the indicator math
(`relative_strength_index`, `cumulative_return`, ...) and weight-combination helpers
that generated `_node_*` functions call into. Kept separate from the code generator
itself so the generated Python only has one small, readable import to depend on.

A price series is just `Sequence[float]`, chronological ascending (oldest first,
most recent/current last) -- e.g. daily closes. Every indicator function reads
backwards from the end of the series, consistent with how the strategy is evaluated
"as of today" using a trailing window.

Every name in INDICATOR_FUNCTIONS below is confirmed against 3 real strategies pulled
from a live account (not guessed) -- see the code generator's module docstring for how
and what's still unconfirmed (mainly: step/fn types those 3 strategies happen not to
use). Simple-average conventions, not Wilder-smoothed:
`relative_strength_index()` here averages gains/losses evenly over the window rather
than using Wilder's exponential smoothing, matching the same simplification
`ibkr_client.get_atr()` already makes for ATR elsewhere in this project (see that
function's docstring). The strategy's own engine may compute these indicators slightly
differently -- treat this as a reasonable approximation to sanity-check logic with, not
a bit-for-bit reproduction of the source backtester.
"""

# Deliberately not `from typing import Tuple`: QuantConnect Cloud's Python environment
# (used by the generated code when backtested via Lean) resolves a
# bare `Tuple` to .NET's System.Tuple via its interop stubs, colliding with typing's.
# `tuple[...]` (lowercase, PEP 585) is used in annotations below instead -- safe on any
# Python version because of `from __future__ import annotations` above.


def _window(prices: Sequence[float], window_days: int, extra: int = 0) -> Sequence[float]:
    """The trailing `window_days + extra` prices. `extra` is 1 for indicators that need
    one extra leading data point to compute `window_days` worth of day-over-day change
    (returns, RSI, drawdown)."""
    n = window_days + extra
    if len(prices) < n:
        raise ValueError(f"Need at least {n} price points for a {window_days}-day window, got {len(prices)}.")
    return prices[-n:]


def current_price(prices: Sequence[float], window_days: Optional[int] = None) -> float:
    """`window_days` accepted (and ignored) so every indicator function has the same
    `(prices, window_days)` signature -- simplifies the code generator's call sites."""
    if not prices:
        raise ValueError("Empty price series.")
    return float(prices[-1])


def cumulative_return(prices: Sequence[float], window_days: int) -> float:
    """Percent change from `window_days` ago to the most recent price."""
    w = _window(prices, window_days, extra=1)
    start, end = w[0], w[-1]
    return (end / start - 1.0) * 100.0


def moving_average_price(prices: Sequence[float], window_days: int) -> float:
    return statistics.fmean(_window(prices, window_days))


def moving_average_return(prices: Sequence[float], window_days: int) -> float:
    """Mean of day-over-day percent returns over the trailing window."""
    w = _window(prices, window_days, extra=1)
    returns = [(w[i] / w[i - 1] - 1.0) * 100.0 for i in range(1, len(w))]
    return statistics.fmean(returns)


def exponential_moving_average_price(prices: Sequence[float], window_days: int) -> float:
    """Standard EMA (alpha = 2/(window_days+1)), seeded with the simple average of the
    earliest `window_days` points then applied forward over whatever history is given
    (not just the trailing window -- EMA is defined recursively over the whole series)."""
    if len(prices) < window_days:
        raise ValueError(f"Need at least {window_days} price points, got {len(prices)}.")
    alpha = 2.0 / (window_days + 1)
    ema = statistics.fmean(prices[:window_days])
    for p in prices[window_days:]:
        ema = alpha * p + (1 - alpha) * ema
    return ema


def standard_deviation_price(prices: Sequence[float], window_days: int) -> float:
    return statistics.pstdev(_window(prices, window_days))


def standard_deviation_return(prices: Sequence[float], window_days: int) -> float:
    w = _window(prices, window_days, extra=1)
    returns = [(w[i] / w[i - 1] - 1.0) * 100.0 for i in range(1, len(w))]
    return statistics.pstdev(returns)


def relative_strength_index(prices: Sequence[float], window_days: int) -> float:
    """Relative Strength Index, 0-100. Simple (not Wilder-smoothed) average of
    gains/losses over the window -- see module docstring."""
    w = _window(prices, window_days, extra=1)
    changes = [w[i] - w[i - 1] for i in range(1, len(w))]
    gains = [c for c in changes if c > 0]
    losses = [-c for c in changes if c < 0]
    avg_gain = sum(gains) / window_days
    avg_loss = sum(losses) / window_days
    if avg_loss == 0:
        return 100.0 if avg_gain > 0 else 50.0
    rs = avg_gain / avg_loss
    return 100.0 - 100.0 / (1.0 + rs)


def max_drawdown(prices: Sequence[float], window_days: int) -> float:
    """Largest peak-to-trough decline over the trailing window, as a positive percent
    (e.g. 12.5 for a 12.5% drawdown)."""
    w = _window(prices, window_days, extra=1)
    peak = w[0]
    worst = 0.0
    for p in w:
        peak = max(peak, p)
        worst = max(worst, (peak - p) / peak)
    return worst * 100.0


INDICATOR_FUNCTIONS = {
    "current-price": current_price,
    "cumulative-return": cumulative_return,
    "moving-average-price": moving_average_price,
    "moving-average-return": moving_average_return,
    "exponential-moving-average-price": exponential_moving_average_price,
    "standard-deviation-price": standard_deviation_price,
    "standard-deviation-return": standard_deviation_return,
    "relative-strength-index": relative_strength_index,
    "max-drawdown": max_drawdown,
}
"""Maps the source's `lhs-fn`/`rhs-fn`/`sort-by-fn` node values to the functions above --
every key here is confirmed (all 9 appear across 3 real strategies pulled from a live
account), not guessed. A 4th strategy could still use an indicator these 3 happen not
to; extend this dict (and add a matching function above, named `fn.replace("-", "_")`)
if the code generator reports an fn name it doesn't recognize."""


COMPARATORS = {
    "gt": lambda a, b: a > b,
    "gte": lambda a, b: a >= b,
    "lt": lambda a, b: a < b,
    "lte": lambda a, b: a <= b,
}
"""The source's `comparator` node value -> a Python comparison. All 4 confirmed (seen
across 3 real strategies); the source may also have an "eq" or similar not observed here."""


def combine_equal(parts: List[Dict[str, float]]) -> Dict[str, float]:
    """Equal-weight combination of sibling subtrees' {ticker: weight} results (each
    summing to ~1.0 on its own) into one {ticker: weight} dict for their shared parent,
    also summing to ~1.0."""
    if not parts:
        return {}
    share = 1.0 / len(parts)
    result: Dict[str, float] = {}
    for part in parts:
        for ticker, weight in part.items():
            result[ticker] = result.get(ticker, 0.0) + weight * share
    return result


def combine_weighted(parts: List[tuple[float, Dict[str, float]]]) -> Dict[str, float]:
    """Like combine_equal(), but each (fraction, {ticker: weight}) pair carries its own
    explicit share (the source's per-child `weight: {num, den}`) instead of an equal 1/n."""
    result: Dict[str, float] = {}
    for fraction, part in parts:
        for ticker, weight in part.items():
            result[ticker] = result.get(ticker, 0.0) + weight * fraction
    return result


def combine_inverse_vol(parts: List[tuple[float, Dict[str, float]]]) -> Dict[str, float]:
    """Inverse-volatility weighting: each (volatility, {ticker: weight}) pair gets a
    share proportional to 1/volatility (higher volatility -> smaller share), normalized
    so shares sum to 1.0. `volatility` is typically standard_deviation_return() computed
    by the generated code for that child over the configured window.

    Approximation, not a confirmed reproduction of the source's own inverse-vol formula
    (e.g. the exact window/lookback used internally is not publicly documented
    as of when this was written) -- treat results as directional, verify against a real
    backtest before trusting exact weights.

    A zero (or negative, shouldn't happen) volatility is floored to a tiny epsilon
    rather than treated as literal infinity or as zero weight -- 1/vol is undefined at
    vol=0, but the *intent* of inverse-vol weighting is "the calmer the asset, the more
    weight it gets", so a perfectly flat price series should end up dominant, not
    excluded."""
    epsilon = 1e-9
    inv = [(1.0 / max(vol, epsilon), part) for vol, part in parts]
    total = sum(w for w, _ in inv)
    if total <= 0:
        return combine_equal([part for _, part in parts])
    result: Dict[str, float] = {}
    for weight, part in inv:
        fraction = weight / total
        for ticker, w in part.items():
            result[ticker] = result.get(ticker, 0.0) + w * fraction
    return result


def select_filter(
    scored: List[tuple[float, Dict[str, float]]], select_fn: str, n: int
) -> Dict[str, float]:
    """The source's 'filter' step: rank candidates by a score (each generated by the
    strategy's configured sort-by-fn/sort-by-fn-params, e.g. cumulative_return over some
    window -- on either a single asset's own price series, or, for a candidate that's a
    whole subtree, a synthetic_price_series() built from its resulting weights) and keep
    only the top or bottom `n`, equal-weighted. select-fn/select-n/sort-by-fn field names
    confirmed from 3 real strategies, but the exact weighting applied among
    multiple *selected* candidates when n > 1 is not separately confirmed; equal-weight
    is the standard convention and what's assumed here."""
    if select_fn == "top":
        ranked = sorted(scored, key=lambda pair: pair[0], reverse=True)
    elif select_fn == "bottom":
        ranked = sorted(scored, key=lambda pair: pair[0])
    else:
        raise ValueError(f"Unknown select-fn {select_fn!r} (expected 'top' or 'bottom').")
    chosen = [part for _, part in ranked[:n]]
    return combine_equal(chosen)


def synthetic_price_series(weights: Dict[str, float], prices: Dict[str, Sequence[float]]) -> List[float]:
    """Builds a synthetic blended price series for a sub-portfolio: each underlying
    ticker's price series is normalized to start at 1.0 over the shared trailing window
    (so different price scales don't distort the blend), then combined according to
    `weights` (e.g. a generated `_node_*` function's {ticker: weight} result, summing to
    ~1.0) into one NAV-style series.

    Used to rank or measure the volatility of a filter/wt-inverse-vol *candidate* that's
    a whole subtree rather than a single asset, confirmed to occur in real strategies
    (a 'filter' whose children are themselves conditional sub-strategies, not plain
    tickers). The source's own exact method for this isn't confirmed -- this is a
    standard, reasonable approximation (a weighted index of normalized prices), not a
    verified reproduction of its internal formula."""
    tickers = [t for t in weights if weights[t] != 0]
    if not tickers:
        raise ValueError("No non-zero-weight tickers to blend into a synthetic series.")
    length = min(len(prices[t]) for t in tickers)
    if length == 0:
        raise ValueError("No overlapping price history among the weighted tickers.")
    normalized = {t: [p / prices[t][-length] for p in prices[t][-length:]] for t in tickers}
    return [sum(weights[t] * normalized[t][i] for t in tickers) for i in range(length)]


NODE_REGISTRY: Dict[str, Callable[[Dict[str, Sequence[float]]], Dict[str, float]]] = {}
"""Populated by generated `_node_*` functions (see the code generator) as each one is
defined, so nodes can call each other via call_node() by name rather than by bare Python
reference. Needed because a large strategy's generated code can be split across multiple
files (some hosting platforms, notably QuantConnect Cloud, cap individual file size at
64,000 characters -- easily exceeded; a complex real strategy can generate 800,000+
characters of Python), and a plain function can only resolve a bare-name call to another
function defined in its own module, not a sibling file's -- a shared registry sidesteps
that entirely, at the cost of one dict lookup per node evaluated."""


def call_node(name: str, prices: Dict[str, Sequence[float]]) -> Dict[str, float]:
    fn = NODE_REGISTRY.get(name)
    if fn is None:
        raise KeyError(
            f"Node function {name!r} was called but never registered in NODE_REGISTRY -- "
            "its defining module wasn't imported before this call. For a multi-file "
            "generated strategy (see generate_python_chunks()), make "
            "sure every chunk module gets imported (even just for its registration side "
            "effect) before run_strategy() is called."
        )
    return fn(prices)
